config/routes.rb
Rails.application.routes.draw do
  resources :blocks

end

app/models/block.rb
class Block < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :set_block, only: [:show, :edit, :update, :destroy]

  # GET /blocks
  # GET /blocks.json
  def index
    @blocks = Block.all
  end

  # GET /blocks/1
  # GET /blocks/1.json
  def show
  end

  # GET /blocks/new
  def new
    @block = Block.new
  end

  # GET /blocks/1/edit
  def edit
  end

  # POST /blocks
  # POST /blocks.json
  def create
    @block = Block.new(block_params)

    respond_to do |format|
      if @block.save
        format.html { redirect_to @block, notice: 'Block was successfully created.' }
        format.json { render :show, status: :created, location: @block }
      else
        format.html { render :new }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blocks/1
  # PATCH/PUT /blocks/1.json
  def update
    respond_to do |format|
      if @block.update(block_params)
        format.html { redirect_to @block, notice: 'Block was successfully updated.' }
        format.json { render :show, status: :ok, location: @block }
      else
        format.html { render :edit }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocks/1
  # DELETE /blocks/1.json
  def destroy
    @block.destroy
    respond_to do |format|
      format.html { redirect_to blocks_url, notice: 'Block was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block
      @block = Block.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def block_params
      params.require(:block).permit(:nombre, :latitud, :longitud, :descripcion, :numSalones)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/_form.html.erb
<%= form_for(@block) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :latitud %><br>
    <%= f.text_field :latitud %>
  </div>
  <div class="field">
    <%= f.label :longitud %><br>
    <%= f.text_field :longitud %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :numSalones %><br>
    <%= f.number_field :numSalones %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<h1>Editing Block</h1>

<%= render 'form' %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blocks</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th>Descripcion</th>
      <th>Numsalones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blocks.each do |block| %>
      <tr>
        <td><%= block.nombre %></td>
        <td><%= block.latitud %></td>
        <td><%= block.longitud %></td>
        <td><%= block.descripcion %></td>
        <td><%= block.numSalones %></td>
        <td><%= link_to 'Show', block %></td>
        <td><%= link_to 'Edit', edit_block_path(block) %></td>
        <td><%= link_to 'Destroy', block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Block', new_block_path %>

app/views/blocks/new.html.erb
<h1>New Block</h1>

<%= render 'form' %>

<%= link_to 'Back', blocks_path %>

app/views/blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @block.nombre %>
</p>

<p>
  <strong>Latitud:</strong>
  <%= @block.latitud %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @block.longitud %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @block.descripcion %>
</p>

<p>
  <strong>Numsalones:</strong>
  <%= @block.numSalones %>
</p>

<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Back', blocks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MapUDb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>